// Mock recommendation data — de-identified template/boilerplate text.
// Mirrors the `recommendations` table schema (see architecture doc, Section 4).
// Swap for real Supabase data once the UI is approved.

export const mockRecommendations = [
  {
    id: 'rec-1',
    drp: 'ESCALATE TX: change to high intensity statin',
    pat_asmt: '[GENERIC_NAME_DOSE:TRIGGERED:rule:LDL_ABOVE_GOAL] Your recent lab results show your cholesterol (LDL) is above the recommended goal for your risk level.',
    pat_rec: 'Talk to your doctor about switching to a higher-intensity statin, such as [GENERIC_NAME_DOSE:HIGH_INTENSITY_STATIN].',
    md_asmt: 'Patient LDL 142 mg/dL, above goal of <100 mg/dL given ASCVD risk category. Currently on [GENERIC_NAME_DOSE:MODERATE_INTENSITY_STATIN].',
    md_rec: 'Consider escalating to [GENERIC_NAME_DOSE:HIGH_INTENSITY_STATIN] daily. Recheck lipid panel in 4-12 weeks.',
    condensed_title: 'Escalate statin therapy',
    condensed_snippet: 'LDL above goal on current moderate-intensity statin. Consider escalating to high-intensity therapy.',
    category: 'Escalate TX',
    tags: ['cardiology', 'lipids'],
    scenario_id: 'scenario-1',
  },
  {
    id: 'rec-2',
    drp: 'ADHERENCE: missed refill on maintenance medication',
    pat_asmt: 'Pharmacy records show a gap in refills for [GENERIC_NAME_DOSE:MAINTENANCE_MED] over the last 60 days.',
    pat_rec: 'If you have stopped taking this medication or are having trouble affording or picking up refills, let your care team know.',
    md_asmt: 'Proportion of days covered (PDC) for [GENERIC_NAME_DOSE:MAINTENANCE_MED] is 58% over the trailing 90 days, below the 80% adherence threshold.',
    md_rec: 'Outreach to assess adherence barriers (cost, side effects, forgetfulness). Consider 90-day supply or refill sync program.',
    condensed_title: 'Medication adherence gap',
    condensed_snippet: 'Refill gap detected for a maintenance medication. PDC below 80% adherence threshold.',
    category: 'Adherence',
    tags: ['adherence', 'pharmacy'],
    scenario_id: 'scenario-2',
  },
  {
    id: 'rec-3',
    drp: 'LAB MONITORING: overdue A1C recheck',
    pat_asmt: 'It has been more than 6 months since your last A1C (blood sugar) test.',
    pat_rec: 'Schedule a lab visit to recheck your A1C so your care team can confirm your diabetes management plan is working.',
    md_asmt: 'Last A1C recorded 7.5 months ago at 8.1%. No repeat lab on file since. Patient on [GENERIC_NAME_DOSE:ORAL_ANTIDIABETIC].',
    md_rec: 'Order repeat A1C. If still >8%, consider intensifying therapy per ADA guidelines.',
    condensed_title: 'A1C recheck overdue',
    condensed_snippet: 'Last A1C was 7.5 months ago and above goal. Repeat lab recommended.',
    category: 'Lab Monitoring',
    tags: ['diabetes', 'labs'],
    scenario_id: 'scenario-3',
  },
  {
    id: 'rec-4',
    drp: 'DEPRESCRIBE: potentially unnecessary duplicate therapy',
    pat_asmt: 'Our records show you may be taking two medications from the same drug class: [GENERIC_NAME_DOSE:DRUG_A] and [GENERIC_NAME_DOSE:DRUG_B].',
    pat_rec: 'Ask your doctor or pharmacist whether both medications are still needed, or if one could be stopped.',
    md_asmt: 'Patient filled overlapping prescriptions for [GENERIC_NAME_DOSE:DRUG_A] and [GENERIC_NAME_DOSE:DRUG_B], both proton pump inhibitors, for 45+ days.',
    md_rec: 'Review indication for dual PPI therapy. Consider discontinuing one agent unless clinically justified (e.g. Barrett\'s esophagus).',
    condensed_title: 'Duplicate therapy review',
    condensed_snippet: 'Two overlapping medications from the same drug class filled concurrently for 45+ days.',
    category: 'Deprescribing',
    tags: ['polypharmacy'],
    scenario_id: 'scenario-4',
  },
  {
    id: 'rec-5',
    drp: 'ESCALATE TX: uncontrolled blood pressure on single agent',
    pat_asmt: 'Your recent blood pressure readings are above the target range for your health profile.',
    pat_rec: 'Ask your doctor whether adding a second blood pressure medication would help you reach your goal.',
    md_asmt: 'Average BP over last 3 readings: 148/92. Currently on monotherapy [GENERIC_NAME_DOSE:ACE_INHIBITOR].',
    md_rec: 'Consider adding [GENERIC_NAME_DOSE:THIAZIDE_DIURETIC] or [GENERIC_NAME_DOSE:CCB] per guideline-directed combination therapy.',
    condensed_title: 'Uncontrolled blood pressure',
    condensed_snippet: 'BP averaging 148/92 on monotherapy. Consider adding a second antihypertensive agent.',
    category: 'Escalate TX',
    tags: ['cardiology', 'hypertension'],
    scenario_id: 'scenario-5',
  },
  {
    id: 'rec-6',
    drp: 'ADHERENCE: early refill pattern suggesting possible overuse',
    pat_asmt: 'Pharmacy records show [GENERIC_NAME_DOSE:CONTROLLED_MED] has been refilled earlier than expected several times.',
    pat_rec: 'If you are taking more than prescribed or running out early, talk to your prescriber about your treatment plan.',
    md_asmt: 'Three consecutive early refills (7-10 days early) for [GENERIC_NAME_DOSE:CONTROLLED_MED] over the last 90 days.',
    md_rec: 'Review PDMP data and discuss use pattern with patient. Consider treatment plan reassessment.',
    condensed_title: 'Early refill pattern',
    condensed_snippet: 'Three early refills in 90 days for a controlled medication. Use pattern review recommended.',
    category: 'Adherence',
    tags: ['adherence', 'controlled-substance'],
    scenario_id: 'scenario-6',
  },
  {
    id: 'rec-7',
    drp: 'LAB MONITORING: statin therapy without recent liver panel',
    pat_asmt: 'It has been over a year since your last liver function test while taking a cholesterol medication.',
    pat_rec: 'Ask your care team whether you are due for routine bloodwork to monitor your medication.',
    md_asmt: 'Patient on [GENERIC_NAME_DOSE:STATIN] for 14 months with no LFT panel on file since initiation.',
    md_rec: 'Order baseline/routine LFT panel per monitoring protocol.',
    condensed_title: 'Liver panel monitoring due',
    condensed_snippet: 'No liver function test on file since starting statin therapy 14 months ago.',
    category: 'Lab Monitoring',
    tags: ['labs', 'cardiology'],
    scenario_id: 'scenario-7',
  },
  {
    id: 'rec-8',
    drp: 'DEPRESCRIBE: long-term PPI use without documented indication',
    pat_asmt: 'You have been taking [GENERIC_NAME_DOSE:PPI] for an extended period.',
    pat_rec: 'Ask your doctor if you still need this medication, or if the dose could be reduced.',
    md_asmt: 'Patient on [GENERIC_NAME_DOSE:PPI] continuously for 18 months. No GERD/Barrett\'s diagnosis documented.',
    md_rec: 'Attempt taper or discontinuation trial; reassess symptoms after 2-4 weeks off therapy.',
    condensed_title: 'Long-term PPI use review',
    condensed_snippet: '18 months of continuous PPI use with no documented indication on file.',
    category: 'Deprescribing',
    tags: ['polypharmacy', 'gi'],
    scenario_id: 'scenario-8',
  },
]

export const categories = [...new Set(mockRecommendations.map((r) => r.category))]
